// Pathway3.js
import React from 'react';
import './PathwayStyles.css'; // Import custom styles for gradient radio button

const Question = ({ question, questionId, onAnswerChange, answer, placeholder }) => {
  return (
    <div className="mb-8">
      <p className="text-lg font-semibold mb-2">{question}</p>
      
      <div className="flex space-x-4 mb-2">
        {["Planned", "Ongoing", "Completed", "Not in Focus"].map((option) => (
          <label key={option} className="flex items-center">
            <input
              type="radio"
              name={questionId}
              value={option}
              checked={answer === option}
              onChange={(e) => onAnswerChange(questionId, e.target.value)}
              className="mr-2 custom-radio" // Custom radio style
              required
            />
            {option}
          </label>
        ))}
      </div>

      <textarea
        placeholder={placeholder}
        className="w-full p-2 border rounded-md text-gray-700 dark:bg-gray-800 dark:text-gray-200 mt-2"
        rows="4"
        onChange={(e) => onAnswerChange(`${questionId}_observation`, e.target.value)}
      ></textarea>
    </div>
  );
};

const Pathway3 = ({ onNext, onBack }) => {
  const [answers, setAnswers] = React.useState({});

  const handleAnswerChange = (questionId, value) => {
    setAnswers((prevAnswers) => ({
      ...prevAnswers,
      [questionId]: value,
    }));
  };

  return (
    <div className="p-6 bg-white dark:bg-gray-900 text-gray-800 dark:text-gray-100 rounded-lg shadow-md">
      <h1 className="text-2xl font-bold mb-6">Pathway-3: Food Supply Chain</h1>
      <p className="mb-6 text-sm text-gray-500 dark:text-gray-400">
        If in addition to primary production, storage, trade, packaging, and processing, retail and marketing of food also follow the principles of recycling and reduction of external inputs, the whole food supply chain will be more sustainable...
      </p>

      {/* Questions for Pathway 3 */}
      <h2 className="text-xl font-bold mb-4">Principle-1: Storage and Trade</h2>
      <Question
        question="Q-3.1) Does the project actively focus on measures that lead to reduction in food loss and waste in the supply chain?"
        questionId="Q3.1"
        answer={answers["Q3.1"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-2: Packaging and Processing</h2>
      <Question
        question="Q-3.2) Does the project actively focus on measures that lead to lessening environmental footprint of packaging and processing activities?"
        questionId="Q3.2"
        answer={answers["Q3.2"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <Question
        question="Q-3.3) Does the project actively focus on food fortification in traditional and mixed food systems?"
        questionId="Q3.3"
        answer={answers["Q3.3"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-3: Retail and Marketing</h2>
      <Question
        question="Q-3.4) Does the project actively focus on facilitating fair participation of the smallholders in the markets?"
        questionId="Q3.4"
        answer={answers["Q3.4"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-4: Recycling (P-3)</h2>
      <Question
        question="Q-3.5) Does the project actively focus on recycling of waste and effluents generated by the food supply chain within a landscape?"
        questionId="Q3.5"
        answer={answers["Q3.5"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-5: Reduction of External Inputs (P-3)</h2>
      <Question
        question="Q-3.6) Does the project actively focus on reducing the dependence of the food supply chain on external inputs within the landscape?"
        questionId="Q3.6"
        answer={answers["Q3.6"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-6: Food Supply Chains</h2>
      <Question
        question="Q-3.7) Does the project actively focus on making the food supply chain more sustainable and robust?"
        questionId="Q3.7"
        answer={answers["Q3.7"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-7: Physical Access to Food</h2>
      <Question
        question="Q-3.8) Does the project actively focus on promoting access points for healthy & safe foods within the landscape?"
        questionId="Q3.8"
        answer={answers["Q3.8"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-8: Economic Access to Food (Affordability)</h2>
      <Question
        question="Q-3.9) Does the project actively focus on ensuring affordability of healthy & safe foods within the landscape?"
        questionId="Q3.9"
        answer={answers["Q3.9"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-9: Acceptability (P-3)</h2>
      <Question
        question="Q-3.10) Does the project actively focus on matching the supply of local food to the preferences of people?"
        questionId="Q3.10"
        answer={answers["Q3.10"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-10: Promotion, Information, Guidelines, and Advertising (P-3)</h2>
      <Question
        question="Q-3.11) Does the project actively focus on promoting healthy food through IEC?"
        questionId="Q3.11"
        answer={answers["Q3.11"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-11: Connectivity (P-3)</h2>
      <Question
        question="Q-3.12) Does the project actively focus on building direct connection between producers and local consumers?"
        questionId="Q3.12"
        answer={answers["Q3.12"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      <h2 className="text-xl font-bold mb-4">Principle-12: Fairness (P-3)</h2>
      <Question
        question="Q-3.13) Does the project actively focus on promoting fair trade practices?"
        questionId="Q3.13"
        answer={answers["Q3.13"]}
        onAnswerChange={handleAnswerChange}
        placeholder="You may skip this question. If you wish to substantiate your choice of response..."
      />

      {/* Navigation Buttons */}
      <div className="flex space-x-4 mt-6">
        <button
          type="button"
          onClick={onBack}
          className="w-full py-3 px-4 rounded-md bg-gray-400 text-white hover:bg-gray-500 transition-colors duration-300"
        >
          Back
        </button>
        <button
          type="button"
          onClick={onNext}
          className="w-full py-3 px-4 rounded-md bg-gradient-to-r from-red-500 to-red-700 text-white hover:from-red-600 hover:to-red-800 transition-colors duration-300"
        >
          Next
        </button>
      </div>
    </div>
  );
};

export default Pathway3;